New Backend QA Static Checks (#100)
Added the following backend static checks to the on-demand backend QA script and the CI configuration:
- ruff format checker

Added the following backend static checks to the on-demand backend QA script only until the findings and solutions to the previous errors are reviewed with the developer:
- mypy static type checker

Updated documentation to provide the commands to automatically resolve ruff linter and ruff formatting checks for issues that can be automatically resolved.
Updated secret_key_generator.py to resolve a ruff formatting check issue using the automated resolution.

Made minor changes to the backend production code ((backend/app/blocklist.py, backend/app/utils/startup.py, backend/app/utils/storage.py ), and qa-requirements.txt to resolve the following errors that were identified by mypy:

- backend\app\blocklist.py:3: error: Need type annotation for "TOKEN_BLOCKLIST" (hint: "TOKEN_BLOCKLIST: set[] = ...") [var-annotated]
- backend\app\utils\storage.py:9: error: Skipping analyzing "boto3": module is installed, but missing library stubs or py.typed marker [import-untyped]
- backend\app\utils\storage.py:58: error: Argument "Bucket" to "generate_presigned_post" of "S3Client" has incompatible type "str | None"; expected "str" [arg-type]
- backend\app\utils\storage.py:87: error: Argument "Bucket" to "head_object" of "S3Client" has incompatible type "str | None"; expected "str" [arg-type]
- backend\app\utils\storage.py:96: error: Argument "Bucket" to "put_object" of "S3Client" has incompatible type "str | None"; expected "str" [arg-type]
- backend\app\utils\startup.py:8: error: Skipping analyzing "botocore.exceptions": module is installed, but missing library stubs or py.typed marker [import-untyped]
- backend\app\utils\startup.py:18: error: Argument "Bucket" to "head_bucket" of "S3Client" has incompatible type "str | None"; expected "str" [arg-type]
- backend\app\utils\startup.py:22: error: Argument "Bucket" to "create_bucket" of "S3Client" has incompatible type "str | None"; expected "str" [arg-type]
- backend\app\utils\startup.py:39: error: Argument "Bucket" to "put_bucket_policy" of "S3Client" has incompatible type "str | None"; expected "str" [arg-type]
- backend\tests\conftest.py:24: error: Skipping analyzing "sqlalchemy_utils": module is installed, but missing library stubs or py.typed marker [import-untyped]